### ISSUE TITLE
TypeLoadException when try run test example

### ISSUE THREAD

**Issue by dmitriyparasochka** [kkokosa/Tune#18]
I've donwloaded realese version of app from https://1drv.ms/u/s!ApZOZuEUCC2DjZhc0vmj9P-6JCmqOQ. When I tried to execute sample code and I get the error:

Message: 
Method 'get_ReferenceDirectiveMap' in type 'Microsoft.CodeAnalysis.CSharp.CSharpCompilation' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

StackTrace:
   at Tune.Core.DiagnosticEngine.Compile(String script, DiagnosticAssemblyMode mode, DiagnosticAssembyPlatform platform)
   at Tune.UI.MainView.RunAsync(Object parameters) in C:\Projects\Tune\Tune.UI\MainView.cs:line 224
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Piatkosia** [comment]
Same here:(

**Comment by Piatkosia** [comment]
Ok, so problem was occured when you have no dev express on your PC.  
You can download compiled version from https://onedrive.live.com/?authkey=%21ANL5o_T_uiQpqjk&id=832D0814E1664E96%21103&cid=832D0814E1664E96 (I hope - Konrad has no problem with this - I copied link from his blog)

**Comment by dmitriyparasochka** [comment]
@Piatkosia  Thanks for your help!

**Comment by kkokosa** [comment]
Indeed a compiled version was old and required DevExpress. Current master version is WPF-based without DevExpress dependency and should compile within VS2015. Thanks @Piatkosia for help.
